# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MplMainWindow(object):
    def setupUi(self, MplMainWindow):
        MplMainWindow.setObjectName("MplMainWindow")
        MplMainWindow.resize(690, 534)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("logo.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.On)
        MplMainWindow.setWindowIcon(icon)
        self.mplcentralwidget = QtWidgets.QWidget(parent=MplMainWindow)
        self.mplcentralwidget.setObjectName("mplcentralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.mplcentralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.mpl = MplWidget(parent=self.mplcentralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mpl.sizePolicy().hasHeightForWidth())
        self.mpl.setSizePolicy(sizePolicy)
        self.mpl.setObjectName("mpl")
        self.verticalLayout.addWidget(self.mpl)
        self.mplhorizontalLayout = QtWidgets.QHBoxLayout()
        self.mplhorizontalLayout.setObjectName("mplhorizontalLayout")
        self.start_button = QtWidgets.QPushButton(parent=self.mplcentralwidget)
        self.start_button.setObjectName("start_button")
        self.mplhorizontalLayout.addWidget(self.start_button)
        self.stop_button = QtWidgets.QPushButton(parent=self.mplcentralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stop_button.sizePolicy().hasHeightForWidth())
        self.stop_button.setSizePolicy(sizePolicy)
        self.stop_button.setObjectName("stop_button")
        self.mplhorizontalLayout.addWidget(self.stop_button)
        self.toggle_button = QtWidgets.QPushButton(parent=self.mplcentralwidget)
        self.toggle_button.setObjectName("toggle_button")
        self.mplhorizontalLayout.addWidget(self.toggle_button)
        self.verticalLayout.addLayout(self.mplhorizontalLayout)
        MplMainWindow.setCentralWidget(self.mplcentralwidget)
        self.mplmenubar = QtWidgets.QMenuBar(parent=MplMainWindow)
        self.mplmenubar.setGeometry(QtCore.QRect(0, 0, 690, 21))
        self.mplmenubar.setObjectName("mplmenubar")
        MplMainWindow.setMenuBar(self.mplmenubar)
        self.mplactionOpen = QtGui.QAction(parent=MplMainWindow)
        self.mplactionOpen.setObjectName("mplactionOpen")
        self.mplactionQuit = QtGui.QAction(parent=MplMainWindow)
        self.mplactionQuit.setObjectName("mplactionQuit")

        self.retranslateUi(MplMainWindow)
        QtCore.QMetaObject.connectSlotsByName(MplMainWindow)

    def retranslateUi(self, MplMainWindow):
        _translate = QtCore.QCoreApplication.translate
        MplMainWindow.setWindowTitle(_translate("MplMainWindow", "Tim\'s EcmoGui"))
        self.start_button.setText(_translate("MplMainWindow", "Start"))
        self.stop_button.setText(_translate("MplMainWindow", "Stop"))
        self.toggle_button.setText(_translate("MplMainWindow", "Toggle"))
        self.mplactionOpen.setText(_translate("MplMainWindow", "Open"))
        self.mplactionQuit.setText(_translate("MplMainWindow", "Quit"))
from mplwidget import MplWidget
